config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forms
  resources :destinations
  resources :comments
  resources :guidebooks
  root 'welcome#index'

  mount MailyHerald::Webui::Engine => "/maily_webui"

  resources :backgrounds
  resources :collaborators
  resources :customers
  resources :tour_pictures
  resources :bank_accounts do
    member do
      get 'activate', to: 'bank_accounts#activate', as: 'activate'
    end
  end
  resources :marketplaces do
    member do
      get 'activate', to: 'marketplaces#activate', as: 'activate'
      get 'update_account', to: 'marketplaces#update_account', as: 'update_account'
      get 'request_external_payment_type_auth', to: 'marketplaces#request_external_payment_type_auth', as: 'request_external_payment_type_auth'
      get 'redirect', to: 'marketplaces#redirect', as: 'redirect'
    end
  end
  resources :translations

  resources :packages
  resources :services

  get 'tags/index'
  get 'languages/index'
  get 'places', to: 'wheres#place', as: 'places'

  get 'contacts/index'
  post 'contacts/send_form'
  post 'contacts/send_message'

  get 'welcome/organizer', to: 'welcome#organizer', as: 'organizer_welcome'
  get 'welcome/user', to: 'welcome#user', as: 'user_welcome'

  resources :orders

  resources :wheres

  post 'webhook', to: 'orders#webhook'
  post 'webhook_external_payment', to: 'orders#webhook_external_payment'
  post 'redirect_external', to: 'orders#redirect_external'
  get 'new_webhook', to: 'orders#new_webhook'
  get 'redirect', to: 'marketplaces#redirect'

  get 'flights/nearest_airports', to: 'flights#nearest_airports'

  get 'organizers/create_from_auth', to: 'organizers#create_from_auth', as: 'create_from_auth'
  get 'organizers/invite', to: 'organizers#invite', as: 'invite'
  get 'organizers/accept_invite/(:id)/(:token)', to: 'organizers#accept_invite', as: 'accept_invite'
  post 'organizers/send_invite', to: 'organizers#send_invite', as: 'send_invite'

  resources :organizers do
    member do
      get 'manage/tours/(:tour)', to: 'organizers#manage_tours', as: 'manage_tours'
      get 'manage/guidebooks/(:guidebook)', to: 'organizers#manage_guidebooks', as: 'manage_guidebooks'
      get 'marketplace', to: 'organizers#marketplace', as: 'marketplace'
      get 'transfer', to: 'organizers#transfer', as: 'transfer'
      post 'transfer_funds', to: 'organizers#transfer_funds', as: 'transfer_funds'
      get 'tos_acceptance', to: 'organizers#tos_acceptance', as: 'tos_acceptance'
      post 'tos_acceptance_confirm', to: 'organizers#tos_acceptance_confirm', as: 'tos_acceptance_confirm'
      get 'dashboard', to: 'organizers#dashboard', as: 'dashboard'
      get 'account', to: 'organizers#account', as: 'account'
      get 'account_edit', to: 'organizers#account_edit', as: 'account_edit'
      get 'profile_edit', to: 'organizers#profile_edit', as: 'profile_edit'
      get 'bank_account_edit', to: 'organizers#bank_account_edit', as: 'bank_account_edit'
      get 'account_status', to: 'organizers#account_status', as: 'account_status'
      get 'confirm_account', to: 'organizers#confirm_account', as: 'confirm_account'
      get 'guided_tour', to: 'organizers#guided_tour', as: 'guided_tour'
      get 'guidebooks', to: 'organizers#guidebooks', as: 'guidebooks'
      get 'schedule', to: 'organizers#schedule', as: 'schedule'
      get 'clients', to: 'organizers#clients', as: 'clients'
      get 'external_events', to: 'organizers#external_events', as: 'external_events'
      post 'import_events', to: 'organizers#import_events', as: 'import_events'
      get 'edit_guided_tour/(:tour)', to: 'organizers#edit_guided_tour', as: 'edit_guided_tour'
      get 'edit_guidebook/(:guidebook)', to: 'organizers#edit_guidebook', as: 'edit_guidebook'
    end
  end

  get 'tours/products', to: 'tours#products'
  get 'tours/products/:id', to: 'tours#product', as: 'tour_product'
  get 'tours/product_availability/:code', to: 'tours#product_availability'
  post 'tours/confirm_product', to: 'tours#confirm_product'
  post 'tours/confirm_product_booking', to: 'tours#confirm_product_booking'

  resources :tours do
    member do
      get 'confirm/(:packagename)', to: 'tours#confirm', as: 'confirm'
      get 'copy_tour', to: 'tours#copy_tour', as: 'copy_tour'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'show_interest', to: 'tours#show_interest'
    end
  end

  resources :guidebooks do
    member do
      get 'confirm/(:packagename)', to: 'guidebooks#confirm', as: 'confirm'
      get 'copy_guidebook', to: 'guidebooks#copy_guidebook', as: 'copy_guidebook'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'manage/guidebook/(:guidebook)', to: 'organizers#guidebook', as: 'manage'
    end
  end

  post 'subscribers/create'

  devise_for :users, :controllers => {
    :passwords => "users/passwords",
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions"
  }

  resources :users do
    member do
      get 'follow', to: 'users#follow'
      get 'unfollow', to: 'users#unfollow'
    end
  end

  get 'logos' => 'welcome#logos'
  get 'manifest' => 'welcome#manifest'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'privacy' => 'welcome#privacy'
  get 'defs' => 'welcome#defs'
  get 'faq' => 'welcome#faq'

end

app/models/guidebook.rb
class Guidebook < ActiveRecord::Base
  belongs_to :organizer
  has_and_belongs_to_many :wheres
  belongs_to :user
  belongs_to :form
  belongs_to :category
  has_one :destination
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :packages, dependent: :destroy
  has_and_belongs_to_many :services, dependent: :destroy
  has_and_belongs_to_many :comments
  has_and_belongs_to_many :tags

  has_and_belongs_to_many :orders

  accepts_nested_attributes_for :category
  accepts_nested_attributes_for :languages
  accepts_nested_attributes_for :packages, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :services, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :wheres

  scope :publisheds, -> { where(status: 'P') }

  validates_presence_of :value, :if => Proc.new { |a| !a.packages.any? }

  validates_presence_of :title, :organizer, :user

  # This method associates the attribute ":picture" with a file attachment
  has_attached_file :picture, styles: {
      thumbnail: '300x300>',
      square: '400x400#',
      cover: '600x800>',
      medium: '500x500>',
      large: '800x800>',
  }

  has_attached_file :file

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/


  def to_param
    "#{id} #{title}".parameterize
  end

  def price
    if !self.try(:value)
      minor = 999999999
      if self.try(:packages) and !self.value
        self.packages.each do |p|
          if !p.nil?
            if p.try(:value)
              minor = p.value if p.value < minor
            end
          end
        end
      end
      return "<small>A partir de R$</small> #{minor}"
    else
      case self.currency
        when 'BRL'
          "<small>R$</small> #{self.value}"
        when 'US'
          self.value
        when 'EURO'
          self.value
        else
          self.value
      end
    end
  end

end

app/controllers/guidebooks_controller.rb
class GuidebooksController < ApplicationController
  before_action :set_guidebook, only: [:show, :edit, :update, :destroy, :copy_guidebook]

  before_action :authenticate_user!, :except => [:show, :index]
  before_filter :check_if_organizer_admin, only: [:create, :update, :destroy]

  # GET /guidebooks
  # GET /guidebooks.json
  def index
    @guidebooks = Guidebook.all
  end

  # GET /guidebooks/1
  # GET /guidebooks/1.json
  def show
  end

  # GET /guidebooks/new
  def new
    @guidebook = Guidebook.new
  end

  # GET /guidebooks/1/edit
  def edit
  end

  # POST /guidebooks
  # POST /guidebooks.json
  def create
    @guidebook = Guidebook.new(guidebook_params)

    respond_to do |format|
      if @guidebook.save
        format.html { redirect_to @guidebook, notice: 'Guidebook was successfully created.' }
        format.json { render :show, status: :created, location: @guidebook }
      else
        format.html {
          flash[:errors] = @guidebook.errors
          flash[:opened] = true
          redirect_to guidebooks_organizer_path(guidebook_params[:organizer] || guidebook_params[:organizer_id]),
                      notice: t('tours_controller_create_notice_two')
        }
        format.json { render json: @guidebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guidebooks/1
  # PATCH/PUT /guidebooks/1.json
  def update
    respond_to do |format|
      if @guidebook.update(guidebook_params)
        format.html { redirect_to @guidebook, notice: 'Guidebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @guidebook }
      else
        format.html {
          puts @guidebook.errors.inspect
          render :edit
        }
        format.json { render json: @guidebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guidebooks/1
  # DELETE /guidebooks/1.json
  def destroy
    @guidebook.destroy
    respond_to do |format|
      format.html { redirect_to guidebooks_url, notice: 'Guidebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def confirm
    @guidebook = Guidebook.find(params[:id])
    @packagename = params[:packagename]

    if @guidebook.value
      @final_price = @guidebook.value
    else
      if params[:package]
        @package = @guidebook.packages.find(params[:package])
        @final_price = @package.value
      elsif @packagename
        @package = @guidebook.packages.find_by_name(@packagename)
        @final_price = @package.value
      else
        @final_price = ""
      end
    end
  end

  def confirm_presence
    @guidebook = Guidebook.find(params[:id])
    @value = params[:value].to_i
    if params[:package]
      @package = @guidebook.packages.find(params[:package])
    elsif params[:packagename]
      @package = @guidebook.packages.find_by_name(params[:packagename])
    else
      @package = nil
    end

    @payment_method = params[:method]

    if params[:amount].nil? || params[:amount].empty?
      @amount = 1
    else
      @amount = params[:amount].to_i
    end

    @services = []
    if params[:guidebook].try(:services_attributes)
      params[:guidebook][:services_attributes].each do |k, v|      
        if v[:value]
          @services << Service.find(v[:id])
        end
      end        
      @sum_services = @services.reduce(0) do |sum, s|
        sum + s.value
      end    
      @value += @sum_services
    end
    
    if params[:final_price].nil? || params[:final_price].empty?
      @final_price = @value
    else
      @final_price = params[:final_price].to_i
    end

    begin
      valid_birthdate = params[:birthdate].to_date
    rescue => e
      puts e.inspect
      @confirm_headline_message = t("tours_controller_headline_msg")
      @confirm_status_message = t("tours_controller_status_msg")
      @status = t('status_danger')
      return
    end

    if @tour.try(:description)
      @desc = @guidebook.try(:description).first(250)
    else
      @desc = t('tours_controller_desc',title: @guidebook.title, organizer: @guidebook.organizer.name)
    end

    @organizer_percent = @guidebook.organizer.percent || 1
    @guidebook_total_percent = 0.95 - (@organizer_percent/100.00)

    @price_cents = (@final_price*100).to_i

    @liquid = (@price_cents)*(@guidebook_total_percent)

    @fees = {
        :fee => (@price_cents - @liquid).round.to_i,
        :liquid => @liquid.round.to_i,
        :total => @price_cents
    }

    @new_charge = {
        :currency => "brl",
        :amount => @fees[:total],
        :source => params[:token],
        :description => @desc,
        :metadata => {
            :type => 'guidebook',
            :object_id => @guidebook.id
        }
    }

    if @guidebook.organizer.try(:marketplace)
      if @guidebook.organizer.marketplace.try(:account_id)
        @account_id = @guidebook.organizer.marketplace.account_id
        @new_charge.store(:destination, {
            :account => @account_id,
            :amount => @fees[:liquid]
        })
      end
    end

    begin
      @payment = Stripe::Charge.create(@new_charge)
        #puts payment.inspect
    rescue Stripe::CardError => e
      puts e.inspect
      #puts e.backtrace
      ContactMailer.notify(t('tours_controller_mailer_notify_one', name: current_user.name, email: current_user.email, inspect: e.inspect)).deliver_now
      @confirm_headline_message = t('tours_controller_headline_msg')
      @confirm_status_message = t('tours_controller_status_msg_two')
      @status = t('status_danger')
      return
    rescue => e
      puts e.inspect
      #puts e.backtrace
      ContactMailer.notify(t('tours_controller_mailer_notify_one', name: current_user.name, email: current_user.email, inspect: e.inspect)).deliver_now
      @confirm_headline_message = t('tours_controller_headline_msg')
      @confirm_status_message = t('tours_controller_status_msg_three')
      @status = t('status_danger')
      return
    end

    if @payment.try(:status)
      if @payment.try(:id)
        @order = @guidebook.orders.create(
            :source_id => @payment[:source][:id],
            :own_id => "truppie_#{@guidebook.id}_#{current_user.id}",
            :user => current_user,
            :guidebook => @guidebook,
            :status => @payment[:status],
            :payment => @payment[:id],
            :price => @value.to_i*100,
            :amount => @amount,
            :final_price => @price_cents,
            :liquid => @fees[:liquid],
            :fee => @fees[:fee],
            :payment_method => @payment_method,
            :package => @package,
            :services => @services
        )

        puts "### Order parameters ###"
        puts @order.inspect

        begin
          @guidebook.save()
          @confirm_headline_message = t('tours_controller_confirm_headline_msg')
          @confirm_status_message = t('tours_controller_status_msg_four')
          @status = t('status_success')
        rescue => e
          puts e.inspect
          @confirm_headline_message = t('tours_controller_headline_msg')
          @confirm_status_message = e.message
          @status = t('status_danger')
        end
      else
        @confirm_headline_message = t('tours_controller_headline_msg')
        @confirm_status_message = t('tours_controller_status_msg_five')
        @status = t('status_danger')
        ContactMailer.notify( t(tours_controller_mailer_notify_two , name: current_user.name, email: current_user.email, inspect: @payment.inspect)).deliver_now
      end
    else
      @confirm_headline_message = t('tours_controller_headline_msg')
      @confirm_status_message = t('tours_controller_status_msg_six')
      @status = t('status_danger')
      ContactMailer.notify(t('tours_controller_mailer_notify_three', name: current_user.name, email: current_user.email )).deliver_now
    end

  end

  def copy_guidebook
    organizer = @guidebook.organizer

    old_wheres = @guidebook.wheres
    old_packages = @guidebook.packages
    old_tour = @guidebook

    new_tour = Guidebook.new(old_tour.attributes.merge({:title => "#{@guidebook.title} - copiado", :status => '', :id => ''}))

    new_tour.wheres << old_wheres

    if old_packages.present?
      new_tour.packages << old_packages
    end

    respond_to do |format|
      if new_tour.save
        format.html {
          redirect_to "/organizers/#{organizer.to_param}/guidebooks", flash: {notice: t('guidebooks_controller_copy_success')}
        }
        format.json { render :copy_tour, status: :ok, location: @guidebook }
      else
        format.html {
          puts 'copy guidebook error'
          puts new_tour.errors.inspect
          redirect_to "/organizers/#{organizer.to_param}/guidebooks", flash: {notice: t('guidebooks_controller_copy_error')}
        }
        format.json { render json: @guidebook.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guidebook
      @guidebook = Guidebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guidebook_params

      split_val = ";"
      organizer = params[:guidebook][:organizer_id] || params[:guidebook][:organizer]


      if organizer.class == String
        new_organizer = Organizer.find_by_name(organizer)

        unless new_organizer.nil?
          new_user = new_organizer.user
          params[:guidebook][:user] = new_user
          params[:guidebook][:organizer] = new_organizer
        end
      end

      if params[:guidebook][:tags] == "" or params[:guidebook][:tags].nil?
        params[:guidebook][:tags] = []
      else
        tags_to_array = params[:guidebook][:tags].split(split_val)
        tags = []
        tags_to_array.each do |t|
          tags.push Tag.find_or_create_by(name: t)
        end
        params[:guidebook][:tags] = tags
      end

app/helpers/guidebooks_helper.rb
module GuidebooksHelper
end

app/views/guidebooks/_manage_guidebooks.html.erb
<div class="manage-container">
  <div class="manage-sidebar overlay-effect overlay">
    <h2 class="spaced-down">Roteiros </h2>
    <nav class="scroll">
      <ul class="flex-scroll">
        <% @guidebook.orders.each do |o| %>
        <li class="flex-nav-item">
          <div class="manage-card">
            <div class="manage-card-val">
              Valor: <%= raw o.price %> <br />
            </div>
            <div class="manage-card-val">
              Status: <%= o.status %>
            </div>
             <div class="manage-card-val">
              Método de pagamento: <%= o.payment_method %>
            </div>
             <div class="manage-card-val">
              Destino: <%= o.destination %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/guidebooks/confirm_presence.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div class="spaced-default spaced-default-full">
        <div class="card card-inverse card-<%= @status %> text-xs-center">
          <div class="card-block">
            <blockquote class="card-blockquote">
              <h4>
                <p><%= @confirm_headline_message %></p>
                <p><%= link_to @guidebook.title, guidebook_path(@guidebook) %></p>
              </h4>
              <footer>
                <p><%= @confirm_status_message %></p>
                <% if @status == "success" %>
                    <p><%= t('guidebooks-confirm-presence-message') %><%= link_to t('tours_view_confirm_presence_link_one'), orders_path %>. </p>
                <% else %>
                    <p><%= link_to t('tours_view_confirm_presence_link_two'), confirm_guidebook_path(@guidebook) %></p>
                <% end %>
              </footer>
            </blockquote>
          </div>
        </div>
        <% if @status == "success" %>
            <h3 class="spaced-top"><%= t('tours_view_confirm_presence_h3') %></h3>
            <div class="main-box no-header clearfix">
              <div class="main-box-body clearfix">
                <div class="table-responsive">
                  <table class="table user-list">
                    <thead>
                    <tr>
                      <th class="text-center"><span><%= t('tours_view_confirm_presence_span_one') %></span></th>
                      <th class="text-center"><span><%= t('tours_view_confirm_presence_span_two') %></span></th>
                      <th><span><%= t('tours_view_confirm_presence_span_three') %></span></th>
                      <th><%= t('tours_view_confirm_presence_th_one') %></th>
                      <th><%= t('tours_view_confirm_presence_th_two') %></th>
                      <th><%= t('tours_view_confirm_presence_th_three') %></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                      <td> <span class="user-subhead"><%= link_to @order.guidebook.organizer.name, organizer_path(@order.guidebook.organizer) %></span></td>
                      <td class="text-center"> <%= raw(@order.friendly_status(@order.current_status)) %> </td>
                      <td> <%= @order.payment %> </td>
                      <td ><h3><%= raw final_price_from_cents(@order.price) %></h3> <% if @order.guidebook.try(:packages) %>
                            <% @order.guidebook.packages.each do |p| %>
                                <% if p.value == @order.price %>
                                    Pacote <%= p.name %>
                                <% end %>
                            <% end %>
                        <% end %> </td>
                      <td class="text-center">
                        <h3><%= @amount %></h3>
                      </td>
                      <td class="text-center">
                        <h3><%= raw final_price(@final_price) %></h3>
                      </td>
                    </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/guidebooks/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="form-signin">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <!-- Nav tabs -->
        <div class="card card-block">
          <div class="card-body" style="overflow:hidden;">
            <h3 class="text-center spaced-down">
              <%= t('guidebook-admin-edit-title') %> <small> <%= link_to t('guidebook-admin-edit-link'), guidebooks_path %></small>
            </h3>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="fullscreen_bg" class="fullscreen_bg"/>
</div>

app/views/guidebooks/index.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <% if @guidebooks.any? %>
          <h3 class="light-heading" style="padding: 4px; margin-top: 30px;">Roteiros personalizados</h3>
          <% @guidebooks.publisheds.each do |g| %>
              <%= render partial: 'layouts/guidebook_list', locals: { t: g } %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/guidebooks/new.html.erb
<%= render 'layouts/navbar' %>
<div class="form-signin">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <!-- Nav tabs -->
        <div class="card card-block">
          <div class="card-body" style="overflow:hidden;">
            <h3 class="text-center spaced-down">
              <%= t('guidebook-admin-new-header') %> <small><%= link_to t('guidebook-admin-link-all') , guidebooks_path %></small>
            </h3>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="fullscreen_bg" class="fullscreen_bg"/>
</div>