config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forms
  resources :destinations
  resources :comments
  resources :guidebooks
  root 'welcome#index'

  mount MailyHerald::Webui::Engine => "/maily_webui"

  resources :backgrounds
  resources :collaborators
  resources :customers
  resources :tour_pictures
  resources :bank_accounts do
    member do
      get 'activate', to: 'bank_accounts#activate', as: 'activate'
    end
  end
  resources :marketplaces do
    member do
      get 'activate', to: 'marketplaces#activate', as: 'activate'
      get 'update_account', to: 'marketplaces#update_account', as: 'update_account'
      get 'request_external_payment_type_auth', to: 'marketplaces#request_external_payment_type_auth', as: 'request_external_payment_type_auth'
      get 'redirect', to: 'marketplaces#redirect', as: 'redirect'
    end
  end
  resources :translations

  resources :packages
  resources :services

  get 'tags/index'
  get 'languages/index'
  get 'places', to: 'wheres#place', as: 'places'

  get 'contacts/index'
  post 'contacts/send_form'
  post 'contacts/send_message'

  get 'welcome/organizer', to: 'welcome#organizer', as: 'organizer_welcome'
  get 'welcome/user', to: 'welcome#user', as: 'user_welcome'

  resources :orders

  resources :wheres

  post 'webhook', to: 'orders#webhook'
  post 'webhook_external_payment', to: 'orders#webhook_external_payment'
  post 'redirect_external', to: 'orders#redirect_external'
  get 'new_webhook', to: 'orders#new_webhook'
  get 'redirect', to: 'marketplaces#redirect'

  get 'flights/nearest_airports', to: 'flights#nearest_airports'

  get 'organizers/create_from_auth', to: 'organizers#create_from_auth', as: 'create_from_auth'
  get 'organizers/invite', to: 'organizers#invite', as: 'invite'
  get 'organizers/accept_invite/(:id)/(:token)', to: 'organizers#accept_invite', as: 'accept_invite'
  post 'organizers/send_invite', to: 'organizers#send_invite', as: 'send_invite'

  resources :organizers do
    member do
      get 'manage/tours/(:tour)', to: 'organizers#manage_tours', as: 'manage_tours'
      get 'manage/guidebooks/(:guidebook)', to: 'organizers#manage_guidebooks', as: 'manage_guidebooks'
      get 'marketplace', to: 'organizers#marketplace', as: 'marketplace'
      get 'transfer', to: 'organizers#transfer', as: 'transfer'
      post 'transfer_funds', to: 'organizers#transfer_funds', as: 'transfer_funds'
      get 'tos_acceptance', to: 'organizers#tos_acceptance', as: 'tos_acceptance'
      post 'tos_acceptance_confirm', to: 'organizers#tos_acceptance_confirm', as: 'tos_acceptance_confirm'
      get 'dashboard', to: 'organizers#dashboard', as: 'dashboard'
      get 'account', to: 'organizers#account', as: 'account'
      get 'account_edit', to: 'organizers#account_edit', as: 'account_edit'
      get 'profile_edit', to: 'organizers#profile_edit', as: 'profile_edit'
      get 'bank_account_edit', to: 'organizers#bank_account_edit', as: 'bank_account_edit'
      get 'account_status', to: 'organizers#account_status', as: 'account_status'
      get 'confirm_account', to: 'organizers#confirm_account', as: 'confirm_account'
      get 'guided_tour', to: 'organizers#guided_tour', as: 'guided_tour'
      get 'guidebooks', to: 'organizers#guidebooks', as: 'guidebooks'
      get 'schedule', to: 'organizers#schedule', as: 'schedule'
      get 'clients', to: 'organizers#clients', as: 'clients'
      get 'external_events', to: 'organizers#external_events', as: 'external_events'
      post 'import_events', to: 'organizers#import_events', as: 'import_events'
      get 'edit_guided_tour/(:tour)', to: 'organizers#edit_guided_tour', as: 'edit_guided_tour'
      get 'edit_guidebook/(:guidebook)', to: 'organizers#edit_guidebook', as: 'edit_guidebook'
    end
  end

  get 'tours/products', to: 'tours#products'
  get 'tours/products/:id', to: 'tours#product', as: 'tour_product'
  get 'tours/product_availability/:code', to: 'tours#product_availability'
  post 'tours/confirm_product', to: 'tours#confirm_product'
  post 'tours/confirm_product_booking', to: 'tours#confirm_product_booking'

  resources :tours do
    member do
      get 'confirm/(:packagename)', to: 'tours#confirm', as: 'confirm'
      get 'copy_tour', to: 'tours#copy_tour', as: 'copy_tour'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'show_interest', to: 'tours#show_interest'
    end
  end

  resources :guidebooks do
    member do
      get 'confirm/(:packagename)', to: 'guidebooks#confirm', as: 'confirm'
      get 'copy_guidebook', to: 'guidebooks#copy_guidebook', as: 'copy_guidebook'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'manage/guidebook/(:guidebook)', to: 'organizers#guidebook', as: 'manage'
    end
  end

  post 'subscribers/create'

  devise_for :users, :controllers => {
    :passwords => "users/passwords",
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions"
  }

  resources :users do
    member do
      get 'follow', to: 'users#follow'
      get 'unfollow', to: 'users#unfollow'
    end
  end

  get 'logos' => 'welcome#logos'
  get 'manifest' => 'welcome#manifest'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'privacy' => 'welcome#privacy'
  get 'defs' => 'welcome#defs'
  get 'faq' => 'welcome#faq'

end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController
  include ApplicationHelper
  before_action :set_marketplace, only: [:show, :edit, :update, :destroy, :activate, :update_account, :request_external_payment_type_auth]
  before_action :authenticate_user!
  before_filter :check_if_super_admin, only: [:index, :new, :edit]
  skip_before_action :verify_authenticity_token

  # GET /marketplaces
  # GET /marketplaces.json
  def index
    @marketplaces = Marketplace.all
  end

  # GET /marketplaces/1
  # GET /marketplaces/1.json
  def show
  end

  # GET /marketplaces/new
  def new
    @marketplace = Marketplace.new
  end

  # GET /marketplaces/1/edit
  def edit
  end

  # POST /marketplaces
  # POST /marketplaces.json
  def create
    @marketplace = Marketplace.new(marketplace_params)
    terms = marketplace_params[:terms]
    respond_to do |format|
      if @marketplace.save
        format.html {
          begin
            account = @marketplace.activate
            if account.id
              @response = account
              @marketplace.organizer.update_attributes(:market_place_active => true)
              @organizer = Organizer.find(marketplace_params[:organizer_id])

              @organizer.update_attributes(:marketplace => @marketplace)

              if terms
                if Rails.env.development?
                  ip = "127.0.0.1"
                else
                  ip = request.remote_ip
                end
                @marketplace.accept_terms(ip)
              end
              MarketplaceMailer.activate(@marketplace.organizer).deliver_now
            end
          rescue => e
            flash[:errors] = { :remote => e.message }
            puts e.inspect
            @notice = t('marketplace_controller_notice_remote_account_fail')
            ContactMailer.notify("Tentativa de criar uma conta remota no markeplace #{@marketplace.inspect} e o erro foi #{e.inspect}").deliver_now
          end
          redirect_to :back, notice: @notice or t('marketplace_controller_notice_two')
        }
        format.json { render :show, status: :created, location: @marketplace }
      else
        format.html { 
          flash[:errors] = @marketplace.errors
          redirect_to :back, notice: t("marketplace-data-incorrect")
        }
        format.json { render json: @marketplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marketplaces/1
  # PATCH/PUT /marketplaces/1.json
  def update
    respond_to do |format|
      if @marketplace.update(marketplace_params)
        format.html {
          begin
            terms = marketplace_params[:terms]
            account = @marketplace.update_account
            if account.id
              @response = account
              puts @response.inspect
              @organizer = Organizer.find(marketplace_params[:organizer_id])
              @notice = t('marketplace-controller-notice-update')
              if terms
                if Rails.env.development?
                  ip = "127.0.0.1"
                else
                  ip = request.remote_ip
                end
                if @marketplace.accept_terms(ip)
                  @marketplace.errors.add(:terms, I18n.t('no-terms'))
                end
              end
            end
          rescue => e
            flash[:errors] = { :remote => e.message }
            puts e.inspect
            @notice = t('marketplace_controller_notice_remote_account_fail')
            ContactMailer.notify("Tentativa de atualizar uma conta remota no markeplace #{@marketplace.inspect} e o erro foi #{e.inspect}").deliver_now
          end
          redirect_to :back, notice: @notice
        }
      else
        format.html {
          flash[:errors] = @marketplace.errors
          redirect_to :back, notice: t('marketplace-controller-notice-update-fail')
        }
        format.json { render json: @marketplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketplaces/1
  # DELETE /marketplaces/1.json
  def destroy
    @marketplace.destroy
    respond_to do |format|
      format.html { redirect_to marketplaces_url, notice: t('marketplace_controller_notice_four') }
      format.json { head :no_content }
    end
  end
  
  def activate
    begin
      account = @marketplace.activate
      if account
        if account.id
          @activation_message = t('marketplace_controller_activation_message_one', organizer: @marketplace.organizer.name)
          @activation_status = t('status_success')
          @response = account
          @marketplace.organizer.update_attributes(:market_place_active => true)
          MarketplaceMailer.activate(@marketplace.organizer).deliver_now
        else
          @activation_message = t('marketplace_controller_activation_message_two', organizer: @marketplace.organizer.name)
          @activation_status = t('status_danger')
          @errors = t('marketplace_controller_errors')
        end
      else
        @activation_message = t("marketplace_controller_activation_message_three", organizer: @marketplace.organizer.name)
        @activation_status = t('status_danger')
        @errors = t("marketplace_controller_errors_two")
      end
    rescue => e
        @activation_message = t("marketplace_controller_activation_message_four", organizer: @marketplace.organizer.name)
        @activation_status = t('status_danger')
        @errors = e.message
        puts e.inspect
    end
  end
  
  def update_account
    begin
      account = @marketplace.update_account
      if account
        if account.id
          @activation_message = t("marketplace_controller_activation_message_five", organizer: @marketplace.organizer.name)
          @activation_status = t('status_success')
          @response = account
          MarketplaceMailer.update(@marketplace.organizer).deliver_now
        else
          @activation_message = t("marketplace_controller_activation_message_six", organizer: @marketplace.organizer.name)
          @activation_status = t('status_danger')
          @errors = t('marketplace_controller_errors_three')
        end
      else
        @activation_message = t("marketplace_controller_activation_message_seven", organizer: @marketplace.organizer.name)
        @activation_status = t('status_danger')
        @errors = t("marketplace_controller_errors_four")
      end
    rescue => e
        puts e.inspect
        puts e.backtrace
        @activation_message = t("marketplace_controller_activation_message_eight")
        @activation_status = t('status_danger')
        @errors = e.message
    end
  end

  def request_external_payment_type_auth
    if @marketplace.payment_types.any?
      @authorize = @marketplace.payment_types_authorize
      if @authorize
        if @marketplace.payment_types.first.email && @marketplace.payment_types.first.auth
          @activation_status = "success"
          @activation_message = "Autorização enviada para o cliente com sucesso"
          MarketplaceMailer.request_app_auth(@marketplace).deliver_now
        end
      else
        @activation_status = "danger"
        @activation_message = "Não foi possível tentar autorizar esta conta"
      end
    else
      @activation_status = "danger"
      @activation_message = "Não foi ativada nenhuma forma de pagamento externa associada"
    end
  end

  def redirect
    @notificationCode = params["notificationCode"]
    @pubkey = params["publicKey"]
    if @notificationCode
      response = RestClient.get "https://ws.pagseguro.uol.com.br/v2/authorizations/notifications/#{@notificationCode}?appId=truppie&appKey=CDEF210C5C5C6DFEE4E36FBE9DB6F509"
      xml_to_json_response = Hash.from_xml(response.body).to_json
      puts xml_to_json_response.inspect
      response_json = JSON.parse(xml_to_json_response)
      @payment_type_id = response_json["authorization"]["reference"]
      @email = response_json["authorization"]["authorizerEmail"]
      begin
        @payment_type = PaymentType.find(@payment_type_id)
      rescue ActiveRecord::RecordNotFound
        @payment_type = PaymentType.where(email: @email ).first
      end
      @code = response_json["authorization"]["code"]
      @payment_update = @payment_type.update_attributes({:token => @code})
      if @payment_update
        @activation_status = "success"
        @activation_message = "Sua forma de pagamento pelo #{@payment_type.type_name} foi autorizada com sucesso, agora suas truppies irão oferecer esta nova forma automaticamente"
      else
        @activation_status = "danger"
        @activation_message = "Não foi possvel autorizar o #{@payment_type.type_name} como forma de pagamento. Não encontramos o código enviado pelo serviço"
      end
      ContactMailer.notify("foi enviada uma notificacao <strong>#{@notificationCode}</strong> de autorizacao do pagseguro e consultando obteve <code>#{response.body.inspect}</code> como resposta e pub key #{@pubkey}").deliver_now
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marketplace
      @marketplace = Marketplace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marketplace_params
      #params.fetch(:marketplace, {}).permit(:organizer_id, :terms, :photo, :active, :person_name, :person_lastname, :document_type, :id_number, :id_type, :id_issuer, :id_issuerdate, :birthDate, :street, :street_number, :complement, :district, :zipcode, :city, :state, :country, :token, :account_id, :document_number, :business, :company_street, :compcompany_complement, :company_zipcode, :company_city, :company_state, :company_country, bank_accounts_attributes: [:bank_number, :agency_number, :agency_check_number, :account_number, :account_check_number, :doc_number, :doc_type, :bank_type, :fullname, :active, :marketplace_id]).merge(params[:marketplace])
      params.fetch(:marketplace, {}).permit!
    end
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/views/marketplaces/_form.html.erb
<%= render partial: 'layouts/error_summary', locals: { errors: @marketplace.try(:errors)} %>
<%= form_for @marketplace, class: "form form-signup", multipart: true, role: "form" do |f| %>
  <ul class="nav nav-tabs spaced-down" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Informações sobre a conta</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#business" role="tab">Informações sobre o negócio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#bank_accounts" role="tab">Conta bancária</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#foto" role="tab">Foto</a>
    </li>
    <% if !@marketplace.new_record? %>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#mkt_status" role="tab">Status da conta</a>
    </li>
    <% end %>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#payment_types" role="tab">Pagamento</a>
    </li>
  </ul>
  <div class="tab-content spaced-down">
    <div class="tab-pane active" id="home" role="tabpanel">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><span class="fa fa-newspaper-o"></span>
                    </span>
                    <%= f.label :organizer %>
                    <%= f.select :organizer_id, options_for_select(Organizer.all.map{|s|[s.name, s.id]}, (@marketplace.organizer_id if @marketplace.organizer_id.present?)) %>
                </div>
            </div>
            <fieldset class="form-group">
              <legend>Dados pessoais</legend>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :person_name, placeholder: "Primeiro nome do titular", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :person_lastname, placeholder: "Último nome do titular", class: "form-control" %>
                  </div>
              </div>
            </fieldset>
            <fieldset class="form-group">
              <legend>CPF</legend>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :document_number, placeholder: "Número do documento", class: "form-control" %>
                      <%= f.hidden_field :document_type, value: "CPF" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.date_field :birthDate, placeholder: "Data de nascimento (AAAA/DD/MM)", class: "form-control" %>
                  </div>
              </div>
            </fieldset>
            <fieldset class="form-group">
              <legend>Dados de endereço</legend>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :street, placeholder: "Rua", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :complement, placeholder: "Complemento", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :zipcode, placeholder: "CEP", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :city, placeholder: "Cidade", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :state, placeholder: "Estado", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :country, placeholder: "País (BR)", class: "form-control" %>
                  </div>
              </div>
            </fieldset>
      </div>
      <div class="tab-pane" id="business" role="tabpanel">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><span class="fa fa-newspaper-o"></span>
                    </span>
                    <%= f.label :business %>
                    <%= f.check_box :business, class: "form-control" %>
                </div>
            </div>
            <fieldset class="form-group">
              <legend>Endereço da empresa</legend>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :company_street, placeholder: "Endereço", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :compcompany_complement, placeholder: "Complemento", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :company_zipcode, placeholder: "CEP", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :company_city, placeholder: "Cidade", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :company_state, placeholder: "Estado", class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-location-arrow"></span></span>
                      <%= f.text_field :company_country, placeholder: "País", class: "form-control" %>
                  </div>
              </div>
            </fieldset>
      </div>
      <div class="tab-pane" id="bank_accounts" role="tabpanel">
        <%= f.fields_for :bank_accounts, ([@marketplace.bank_accounts.build] if @marketplace.bank_accounts.empty?) do |ff| %>
        <fieldset class="form-group packages-set">
          <div class="form-group">
              <div class="input-group">
                  <span class="input-group-addon"><span class="fa fa-sticky-note-o"></span></span>
                  <%= ff.select :bank_number, options_for_select(bank_list["banks"].map{|s|[s[1], s[0]]}), :selected => ff.object.bank_number  %>
              </div>
          </div>
          <div class="form-group">
              <div class="input-group">
                  <span class="input-group-addon"><span class="fa fa-sticky-note-o"></span></span>
                  <%= ff.text_field :agency_number, placeholder: "Número da agência", class: "form-control" %>
              </div>
          </div>
          <div class="form-group">
              <div class="input-group">
                  <span class="input-group-addon"><span class="fa fa-sticky-note-o"></span></span>
                  <%= ff.text_field :account_number, placeholder: "Número da conta (xxx-xxxx-x)", class: "form-control" %>
              </div>
          </div>
          <div class="form-group">
              <div class="input-group">
                  <span class="input-group-addon"><span class="fa fa-sticky-note-o"></span></span>
                  <%= ff.text_field :fullname, placeholder: "Nome completo", class: "form-control" %>
              </div>
          </div>
          <div class="form-group">
              <div class="input-group">
                  <%= f.label :active %>
                  <%= ff.check_box :active, class: "form-control" %>
                  <%= ff.hidden_field :marketplace_id, value: @marketplace.id %>
              </div>
          </div>
        </fieldset>
        <% end %>
      </div>
      <div class="tab-pane" id="foto" role="tabpanel">
        <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><span class="fa fa-photo"></span></span>
                    <%= f.file_field :photo, class: "form-control" %>
                </div>
            </div>
            <p>
              <h3>Arquivos enviados</h3>
              <%= @marketplace.uploads.inspect %>
            </p>
            <div class="form-group">
            <% unless @marketplace.nil? %>
                <% if @marketplace.photo.present? %>
                  <%= image_tag @marketplace.photo.url(:thumbnail) %>
                <% end %>
            <% end %>
            </div>
      </div>
      <% if !@marketplace.new_record? %>
      <div class="tab-pane" id="mkt_status" role="tabpanel">
          <% if @marketplace.is_active? %>
            <p>A sua conta se encontra ativa os dados são:</p>
            <ul class="list-unstyled">
              <li>Id da conta: <%= @marketplace.account_id %></li>
              <li>token: <%= @marketplace.token %></li>
            </ul>
            <p>
              <%= @marketplace.account %>
            </p>
            <h3>Contas</h3>
            <%= @marketplace.registered_bank_account %>
            <h3>Pendências</h3>
            <%= @marketplace.account_missing %>
          <% else %>
            <p>A sua conta ainda não está ativa no Marketplace</p>
            <%= link_to 'Ativar no moip', activate_marketplace_path(@marketplace) %>
          <% end %>
      </div>
      <% end %>
      <div class="tab-pane" id="payment_types" role="tabpanel">
        <%= f.fields_for :payment_types, ([@marketplace.payment_types.build] if @marketplace.payment_types.empty?) do |ff| %>
            <fieldset class="form-group">
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><span class="fa fa-sticky-note-o"></span></span>
                  <%= ff.select :type_name, ['pagseguro'] %>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><span class="fa fa-sticky-note-o"></span></span>
                  <%= ff.text_field :email, placeholder: "email da conta", class: "form-control" %>
                </div>
              </div>
            </fieldset>
        <% end %>
      </div>
  </div>
  <div class="pull-right">  
    <a href="<%= new_marketplace_path %> class="btn btn-lg btn-default" role="button" style="margin-right: 40px; margin-top: 10px;">
        Cancelar
      </a>  
      <%= link_to("Salvar marketplace", "#", class: "btn btn-lg btn-primary create-marketplace") %>
  </div>
  <% end %>

app/views/marketplaces/activate.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div class="spaced-default spaced-default-full">
        <% if @activation_status == "danger" %>
        <div class="card card-inverse card-<%= @activation_status %> text-xs-center">
          <div class="card-block">
            <blockquote class="card-blockquote">
              <h4>
                <p><%= @activation_message %></p> 
                <% if !@errors.nil? %>
                <p><%= @errors %></p>
                <% end %>
              </h4>
              <% if !@errors["errors"].nil? %>
              <p>Encontramos os seguintes erros no marketplace cadastrado:</p>
              <ul class="list-unstyled">
                <% @errors["errors"].each do |e| %>
                    <li><%= e["description"] %></li>
                <% end %>
              </ul>
              <% else %>
                <%= @errors["ERRORS"] %>
              <% end %>
              <footer>
                <p><%= link_to 'voltar para os marketplaces', marketplaces_path %></p>
              </footer>
            </blockquote>
          </div>
        </div>
        <% end %>
        <% if @activation_status == "success" %>
        <div class="card card-inverse card-<%= @activation_status %> text-xs-center">
          <div class="card-block">
            <blockquote class="card-blockquote">
              <h4>
                <p><%= @activation_message %></p> 
              </h4>
              <% if @marketplace.is_active? %>
                <p>A sua conta se encontra ativa no MOIP e os dados são:</p>
                <ul class="list-unstyled">
                  <li>id da conta: <%= @marketplace.account_id %></li>
                  <li>token: <%= @marketplace.token %></li>
                </ul>
              <% end %>
              <p>Agora você precisa ativar a conta bancária</p>
              <footer>
                <p><%= link_to 'voltar para os marketplaces', marketplaces_path %></p>
              </footer>
            </blockquote>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/marketplaces/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="form-signin">
<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <!-- Nav tabs -->
            <div class="card card-block">
                <div class="card-body" style="overflow:hidden;">
                    <h3 class="text-center spaced-down">
                        Adicionar Marketplace ou <small><%= link_to 'ver todos', marketplace_path %></small>
                    </h3>
                  <%= render 'form' %>
          </div>
              </div>
          </div>
      </div>
  </div>
</div>
<div id="fullscreen_bg" class="fullscreen_bg"/>
</div>

app/views/marketplaces/new.html.erb
<%= render 'layouts/navbar' %>
<div class="form-signin">
<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <!-- Nav tabs -->
            <div class="card card-block">
                <div class="card-body" style="overflow:hidden;">
                    <h3 class="text-center spaced-down">
                        Adicionar marketplace ou <small><%= link_to 'ver todos', marketplaces_path %></small>
                    </h3>
                  <%= render 'form' %>
                 </div>
              </div>
          </div>
      </div>
  </div>
</div>
<div id="fullscreen_bg" class="fullscreen_bg"/>
</div>