config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forms
  resources :destinations
  resources :comments
  resources :guidebooks
  root 'welcome#index'

  mount MailyHerald::Webui::Engine => "/maily_webui"

  resources :backgrounds
  resources :collaborators
  resources :customers
  resources :tour_pictures
  resources :bank_accounts do
    member do
      get 'activate', to: 'bank_accounts#activate', as: 'activate'
    end
  end
  resources :marketplaces do
    member do
      get 'activate', to: 'marketplaces#activate', as: 'activate'
      get 'update_account', to: 'marketplaces#update_account', as: 'update_account'
      get 'request_external_payment_type_auth', to: 'marketplaces#request_external_payment_type_auth', as: 'request_external_payment_type_auth'
      get 'redirect', to: 'marketplaces#redirect', as: 'redirect'
    end
  end
  resources :translations

  resources :packages
  resources :services

  get 'tags/index'
  get 'languages/index'
  get 'places', to: 'wheres#place', as: 'places'

  get 'contacts/index'
  post 'contacts/send_form'
  post 'contacts/send_message'

  get 'welcome/organizer', to: 'welcome#organizer', as: 'organizer_welcome'
  get 'welcome/user', to: 'welcome#user', as: 'user_welcome'

  resources :orders

  resources :wheres

  post 'webhook', to: 'orders#webhook'
  post 'webhook_external_payment', to: 'orders#webhook_external_payment'
  post 'redirect_external', to: 'orders#redirect_external'
  get 'new_webhook', to: 'orders#new_webhook'
  get 'redirect', to: 'marketplaces#redirect'

  get 'flights/nearest_airports', to: 'flights#nearest_airports'

  get 'organizers/create_from_auth', to: 'organizers#create_from_auth', as: 'create_from_auth'
  get 'organizers/invite', to: 'organizers#invite', as: 'invite'
  get 'organizers/accept_invite/(:id)/(:token)', to: 'organizers#accept_invite', as: 'accept_invite'
  post 'organizers/send_invite', to: 'organizers#send_invite', as: 'send_invite'

  resources :organizers do
    member do
      get 'manage/tours/(:tour)', to: 'organizers#manage_tours', as: 'manage_tours'
      get 'manage/guidebooks/(:guidebook)', to: 'organizers#manage_guidebooks', as: 'manage_guidebooks'
      get 'marketplace', to: 'organizers#marketplace', as: 'marketplace'
      get 'transfer', to: 'organizers#transfer', as: 'transfer'
      post 'transfer_funds', to: 'organizers#transfer_funds', as: 'transfer_funds'
      get 'tos_acceptance', to: 'organizers#tos_acceptance', as: 'tos_acceptance'
      post 'tos_acceptance_confirm', to: 'organizers#tos_acceptance_confirm', as: 'tos_acceptance_confirm'
      get 'dashboard', to: 'organizers#dashboard', as: 'dashboard'
      get 'account', to: 'organizers#account', as: 'account'
      get 'account_edit', to: 'organizers#account_edit', as: 'account_edit'
      get 'profile_edit', to: 'organizers#profile_edit', as: 'profile_edit'
      get 'bank_account_edit', to: 'organizers#bank_account_edit', as: 'bank_account_edit'
      get 'account_status', to: 'organizers#account_status', as: 'account_status'
      get 'confirm_account', to: 'organizers#confirm_account', as: 'confirm_account'
      get 'guided_tour', to: 'organizers#guided_tour', as: 'guided_tour'
      get 'guidebooks', to: 'organizers#guidebooks', as: 'guidebooks'
      get 'schedule', to: 'organizers#schedule', as: 'schedule'
      get 'clients', to: 'organizers#clients', as: 'clients'
      get 'external_events', to: 'organizers#external_events', as: 'external_events'
      post 'import_events', to: 'organizers#import_events', as: 'import_events'
      get 'edit_guided_tour/(:tour)', to: 'organizers#edit_guided_tour', as: 'edit_guided_tour'
      get 'edit_guidebook/(:guidebook)', to: 'organizers#edit_guidebook', as: 'edit_guidebook'
    end
  end

  get 'tours/products', to: 'tours#products'
  get 'tours/products/:id', to: 'tours#product', as: 'tour_product'
  get 'tours/product_availability/:code', to: 'tours#product_availability'
  post 'tours/confirm_product', to: 'tours#confirm_product'
  post 'tours/confirm_product_booking', to: 'tours#confirm_product_booking'

  resources :tours do
    member do
      get 'confirm/(:packagename)', to: 'tours#confirm', as: 'confirm'
      get 'copy_tour', to: 'tours#copy_tour', as: 'copy_tour'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'show_interest', to: 'tours#show_interest'
    end
  end

  resources :guidebooks do
    member do
      get 'confirm/(:packagename)', to: 'guidebooks#confirm', as: 'confirm'
      get 'copy_guidebook', to: 'guidebooks#copy_guidebook', as: 'copy_guidebook'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'manage/guidebook/(:guidebook)', to: 'organizers#guidebook', as: 'manage'
    end
  end

  post 'subscribers/create'

  devise_for :users, :controllers => {
    :passwords => "users/passwords",
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions"
  }

  resources :users do
    member do
      get 'follow', to: 'users#follow'
      get 'unfollow', to: 'users#unfollow'
    end
  end

  get 'logos' => 'welcome#logos'
  get 'manifest' => 'welcome#manifest'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'privacy' => 'welcome#privacy'
  get 'defs' => 'welcome#defs'
  get 'faq' => 'welcome#faq'

end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  has_many :tours
  has_many :guidebooks
  has_and_belongs_to_many :members
  has_and_belongs_to_many :wheres

  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows, source: :user

  belongs_to :marketplace
  
  belongs_to :user
  
  scope :publisheds, -> { where(status: 'P') }

  def to_param
    "#{id} #{name}".parameterize
  end
  
  # This method associates the attribute ":picture" with a file attachment
  has_attached_file :picture, styles: {
    thumbnail: '300x300>',
    square: '400x400#',
    cover: '600x800>',
    medium: '500x500>',
    large: '800x800>',
  }

  validates :name, uniqueness: true

  accepts_nested_attributes_for :tours, allow_destroy: true, reject_if: :all_blank

  accepts_nested_attributes_for :wheres, allow_destroy: true, reject_if: :all_blank

  validates_presence_of :name, :email, :user, :website, :description, allow_blank: false

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  
  def balance
    if self.market_place_active
      begin
        balance = Stripe::Balance.retrieve(self.marketplace.token)
        return balance
      rescue => e
        puts e.inspect
        return false
      end
    else
      false
    end  
  end

  def clients
    clients_array = []
    self.tours.each do |t|
      t.orders.each do |o|
        clients_array.push o.user
      end
    end
    clients_array.uniq
  end

  def verified?
    missing = self.missing.select { |a| true if (a == "description") }
    !missing.any?
  end

  def missing
    missing = []
    self.attributes.each do |a|
      #puts a.inspect
      if a[1].nil? or a[1].blank?
        missing << a[0]
      end
    end
    missing
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  include ApplicationHelper
  before_action :set_organizer, only: [:show, :edit, :update, :destroy, :transfer, :guided_tour, :guidebooks, :external_events, :import_events, :profile_edit, :account, :account_edit, :bank_account_edit, :account_status, :guided_tour, :edit_guided_tour, :schedule, :clients, :confirm_account]
  before_action :authenticate_user!, :except => [:show, :index, :create]
  before_filter :check_if_organizer_admin, only: [:update, :manage_tours, :transfer, :transfer_funds, :tos_acceptance, :tos_acceptance_confirm, :external_events, :import_events, :profile_edit, :account, :account_edit, :bank_account_edit, :account_status, :guided_tour, :edit_guided_tour, :schedule, :clients, :confirm_account]
  before_filter :check_if_super_admin, only: [:new, :edit, :invite, :send_invite]

  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.publisheds
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
    if !!session[:follow]
      current_user.follow(@organizer)
      OrganizerMailer.new_follower(@organizer, current_user).deliver_now
      session[:follow] = nil
    end
  end

  def invite

  end

  def send_invite
    @invited = Organizer.find(params[:invited])
    if @invited
      @invited.update_attributes({:invite_token => SecureRandom.urlsafe_base64})
      OrganizerMailer.invite(@invited).deliver_now
      redirect_to invite_path, :notice => I18n.t('guide-invite-successfull')
    else
      redirect_to invite_path, :notice => I18n.t('guide-invite-fail')
    end
  end

  def accept_invite
    @organizer = Organizer.find(params[:id])
    if @organizer.try(:id)
      organizer_token = @organizer.try(:invite_token)
      if organizer_token == params[:token]
        if not user_signed_in?
          redirect_to new_user_session_path, :notice => @notice_message
        else
          if current_user == @organizer.user
            ContactMailer.notify("mensagem para o guia que recebeu o convite: Você já está associado a este perfil de guia").deliver_now
            redirect_to organizer_path(@organizer), :notice => "Você já está associado a este perfil de guia"
          else
            @organizer.user = current_user
            if @organizer.save
              ContactMailer.notify("mensagem para o guia que recebeu o convite: Sua conta de guia foi criada").deliver_now
              redirect_to organizer_path(@organizer), :notice => "Sua conta de guia foi criada"
            else
              ContactMailer.notify("mensagem para o guia que recebeu o convite: Tivemos problema ao associar seu perfil").deliver_now
              redirect_to organizer_path(@organizer), :notice => "Tivemos problema ao associar seu perfil"
            end
          end
        end
      else
        redirect_to root_path, :notice => "Convite inválido"
        return
      end
    else
      redirect_to new_user_session_path, :notice => "Não foi possível encontrar o seu perfil de guia"
      return
    end
  end

  # GET /organizers/new
  def new
    @organizer = Organizer.new
  end

  def guided_tour
    @guided_tour = @organizer.tours.new
    @opened = flash[:opened] || false
    @cats = ["Esportes e aventura", "Trilhas e travessias", "Relax", "Família", "Geek", "Gastronomia", "Urbano", "Cultura"]
  end

  def edit_guidebook
    @guided_tour = Guidebook.find(params[:guidebook])
    @organizer = Organizer.find(params[:id])
    @cats = ["Esportes e aventura", "Trilhas e travessias", "Relax", "Família", "Geek", "Gastronomia", "Urbano", "Cultura"]
    @current_category_name = Category.find(@guided_tour.category_id).name rescue nil
  end

  def guidebooks
    @guided_tour = @organizer.guidebooks.new
    @opened = flash[:opened] || false
    @cats = ["Esportes e aventura", "Trilhas e travessias", "Relax", "Família", "Geek", "Gastronomia", "Urbano", "Cultura"]
  end

  def edit_guided_tour
    @guided_tour = Tour.find(params[:tour])
    @organizer = Organizer.find(params[:id])
    @cats = ["Esportes e aventura", "Trilhas e travessias", "Relax", "Família", "Geek", "Gastronomia", "Urbano", "Cultura"]
    @current_category_name = Category.find(@guided_tour.category_id).name rescue nil
  end

  def profile_edit

  end

  # GET /organizers/1/edit
  def edit

  end

  # POST /organizers
  # POST /organizers.json
  def create

    @organizer = Organizer.new(organizer_params.except! 'type_of_user', 'password', 'password_confirmation')

    if !organizer_params[:user_id] && organizer_params[:type_of_user] === 'organizer'
      sign_up_params = {
          name: organizer_params[:name],
          email: organizer_params[:email],
          password: organizer_params[:password],
          password_confirmation: organizer_params[:password_confirmation],
          type_of_user: organizer_params[:type_of_user]
      }

      temp_user = User.new(sign_up_params)
      if temp_user.save
        sign_in temp_user, :bypass => true
        @organizer.user = temp_user
      else
        puts temp_user.errors.inspect
        flash[:errors] = temp_user.errors
        redirect_to organizer_welcome_path, notice: I18n.t('organizer-create-issue-message')
        return
      end
    end

    respond_to do |format|
      if @organizer.save
        if organizer_params[:email]
          sign_in_mailchimp organizer_params[:email]
        end
        format.html {
          if @organizer.mail_notification
            ContactMailer.notify("Uma nova conta de guia foi criada").deliver_now
            OrganizerMailer.notify(@organizer, "activate").deliver_now
          end
          redirect_to organizer_path(@organizer), notice: I18n.t('organizer-create-success')

        }
        format.json { render :show, status: :created, location: @organizer }

      else
        format.html {
          flash[:errors] = @organizer.errors
          puts @organizer.errors.inspect
          redirect_to organizer_welcome_path, notice: I18n.t('organizer-create-issue-message')
        }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_from_auth
    if session[:organizer_welcome]
      session[:organizer_user_id] = current_user.id

      @organizer = Organizer.find(session[:organizer_id])


      if @organizer.update_attributes(user_id: session[:organizer_user_id])
        redirect_to organizer_path(@organizer), notice: I18n.t('organizer-create-success')
      else
        flash[:errors] = @organizer.errors
        puts 'errors from organizer'
        puts @organizer.errors
        redirect_to organizer_welcome_path, notice: I18n.t('organizer-create-issue-message')
      end
    else
      redirect_to organizer_welcome_path, notice: I18n.t('organizer-create-issue-message')
    end
  end


  # PATCH/PUT /organizers/1
  # PATCH/PUT /organizers/1.json
  def update
    respond_to do |format|
      if @organizer.update(organizer_params)
        format.html {
          #OrganizerMailer.notify(@organizer, "update").deliver_now
          redirect_to :back, notice: I18n.t('organizer-update-sucessfully')
        }
        format.json { render :show, status: :ok, location: @organizer }
      else
        format.html {
          flash[:errors] = @organizer.errors
          redirect_to :back, notice: I18n.t('organizer-update-error')
        }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizers/1
  # DELETE /organizers/1.json
  def destroy
    @organizer.destroy
    respond_to do |format|
      format.html { redirect_to organizers_url, notice: 'Organizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    @organizer = Organizer.find(params[:id])
    @tours = @organizer.tours.order('created_at DESC')
    if params[:tour].nil?
      @tour = @organizer.tours.order('created_at DESC').first
    else
      @tour = Tour.find(params[:tour])
    end
  end

  def manage_tours
    @organizer = Organizer.find(params[:id])
    @tours = @organizer.tours.order('created_at DESC')
    if params[:tour].nil?
      @tour = @organizer.tours.order('created_at DESC').first
    else
      @tour = Tour.find(params[:tour])
    end
    @guidebook = manage_guidebooks
  end

  def manage_guidebooks
    @organizer = Organizer.find(params[:id])
    @guidebooks = @organizer.guidebooks.order('created_at DESC')
    if params[:guidebook].nil?
      @guidebook = @organizer.guidebooks.order('created_at DESC').first
    else
      @guidebook = Guidebook.find(params[:guidebook])
    end
  end

  def schedule
    @organizer = Organizer.find(params[:id])
  end

  def clients
    @organizer = Organizer.find(params[:id])
  end

  def account
    if @organizer.try(:marketplace)
      @missing_info = @organizer.marketplace.account_missing
    else
      @missing_info = {
          marketplace: t("no-marketplace")
      }
    end
  end

  def account_edit
    if @organizer.try(:marketplace)
      @marketplace = @organizer.marketplace
    else
      @marketplace = Marketplace.new
    end
  end

  def bank_account_edit
    @marketplace = @organizer.marketplace
    @bank_account = BankAccount.new
  end

  def account_status
    if @organizer.try(:marketplace)
      @account_missing = @organizer.marketplace.account_needed
    else
      @account_missing = [
          {
              name: "marketplace",
              label: t("marketplace-missing"),
              message: t('no-marketplace-label')
          }
      ]
    end

  end

  def import_events
    events = params["events"]
    @token = params["facebook_token"]
    @user_id = params["facebook_user_id"]

    if !events.nil?
      @response = []
      events.each do |e|
        @response.push JSON.load RestClient.get("https://graph.facebook.com/v2.9/#{e}", :content_type => :json, :accept => :json, :authorization => "OAuth #{@token}")
      end

      @response.each do |r|

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/views/organizers/_organizer_side_menu_account.html.erb
<div class="card">
  <div class="card-block card-organizer">
    <div class="text-xs-center">
      <h4 class="card-title spaced-down">
        <%= render partial: 'layouts/organizer_picture', locals: { organizer: @organizer }%>
        <strong><%= @organizer.name %> </strong>
      </h4>
      <p class="card-text spaced-down"><%= @organizer.description %></p>
      <% if !@organizer.website.nil? %>
          <%= link_to @organizer.website, class: 'btn btn-primary-outline btn-sm', target: "_blank" do %>
              <i class="fa fa-external-link"></i> ir para seu website
          <% end %>
      <% end %>
      <% if !@organizer.email.nil? %>
          <a class="btn btn-primary-outline btn-sm" href="mailto:ola@truppie.com"><i class="fa fa-envelope"></i> dúvida? Envie um e-mail pra gente</a> <br />
      <% end %>
    </div>
  </div>
</div>
<ul class="list-group">
  <li class="list-group-item">
    <a href="<%= profile_edit_organizer_path(@organizer) %>">
      <% if @organizer.verified? %>
          <span class="label label-success label-pill pull-xs-right"><%= t('profile-verified-label') %></span>
      <% else %>
          <span class="label label-warning label-pill pull-xs-right"><%= t('profile-incomplete-label') %></span>
      <% end %>
      <%= t('organizer-profile-edit') %>
    </a>
  </li>
  <li class="list-group-item">
    <a href="<%= account_edit_organizer_path(@organizer) %>">
      <% if @organizer.try(:marketplace) and @organizer.marketplace.is_active? and @organizer.marketplace.account_user_data_verified %>
      <span class="label label-success label-pill pull-xs-right"><%= t('account-verified-label') %></span>
      <% else %>
      <span class="label label-danger label-pill pull-xs-right"><%= t('account-not-verified-label') %></span>
      <% end %>
      <%= t('organizer-account-edit') %>
    </a>
  </li>
  <li class="list-group-item">
    <a href="<%= bank_account_edit_organizer_path(@organizer) %>">
      <% if @organizer.marketplace.try(:bank_account_verified) %>
        <span class="label label-success label-pill pull-xs-right"><%= t('bank-account-verified-label') %></span>
      <% else %>
        <span class="label label-danger label-pill pull-xs-right"><%= t('bank-account-not-verified-label') %></span>
      <% end %>
      <%= t('organizer-bank-data') %>

    </a>
  </li>
</ul>

app/views/organizers/_popover_template_title_content.html.erb
<button type='button' class='closepopover close' data-trigger-elem-id='<%= trigger_elem_id %>' aria-label='Close'>
  <span aria-hidden='true'>&times;</span>
</button>

app/views/organizers/account.html.erb
<%= render 'layouts/navbar' %>
<%= render 'layouts/flash' %>
<div class="container manage-entries">
  <div class="row">
    <div class="col-xs-12">
      <div class="manage-inspiration">
        <%= render 'layouts/organizer_intro_block', locals: {organizer: @organizer} %>
      </div>
      <div class="manage-container">
        <div class="manage-sidebar">
          <%= render partial: 'organizer_side_menu_account' %>
        </div>
        <div class="manage-main">
          <div class="">
            <p class="text-xs-center"><strong><%= t('hello-organizer-welcome', organizer: @organizer.name) %></strong></p>
            <p class="text-xs-center"><%= t('organizer-account-intro-title') %></p>
            <p class="text-xs-center"><%= t('organizer-account-intro-desc') %></p>
            <p class="text-xs-center">
              <%= image_tag("guide-account.svg", :alt => "new truppie", :width => 128, :class => 'img-fluid center-block') %>
            </p>
            <p class="text-xs-center">
              <%= t('organizer-dashboard-desc') %>
            </p>
            <p class="text-xs-center">
              <%= link_to account_edit_organizer_path(@organizer), class: 'btn btn-primary btn-lg' do %>
                  <%= t('organizer-add-account-data') %> <i class="fa fa-edit" style="margin-left: 5px;"></i>
              <% end %>
            </p>
            <p class="text-xs-center">
              <%= link_to guided_tour_organizer_path(@organizer), class: 'btn btn-primary btn-lg' do %>
                  <%= t('organizer-add-tour') %> <i class="fa fa-calendar" style="margin-left: 5px;"></i>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="fullscreen_bg" class="fullscreen_bg"></div>
</div>

app/views/organizers/dashboard.html.erb
<%= render 'layouts/navbar' %>
  <div class="container manage-entries">
    <div class="row">
      <div class="col-xs-12">
        <div class="manage-inspiration">
          <%= render 'layouts/organizer_intro_block', locals: {organizer: @organizer} %>
        </div>
        <div class="manage-container">
          <div class="manage-sidebar">
            <%= render partial: 'organizer_side_menu' %>
          </div>
          <div class="manage-main">
            <div class="row">
              <div class="col-xs-12">
                <p class="text-xs-center"><strong><%= t('hello-organizer-welcome', organizer: @organizer.name) %></strong></p>
                <p class="text-xs-center" style="overflow:hidden; padding-bottom: 40px;"><%= t('organizer-panel-welcome') %></p>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-6">
                <p class="text-xs-center">
                  <%= image_tag("adventurer.svg", :alt => "new truppie", :width => 200, :class => 'img-fluid center-block') %>
                </p>
                <p class="text-xs-center">
                  <%= link_to guided_tour_organizer_path(@organizer), class: 'btn btn-primary btn-lg', data: {turbolinks: false} do %>
                      <%= t('organizer-new-tour') %> <i class="fa fa-plus"></i>
                  <% end %>
                </p>
                <p class="text-xs-center">
                  <%= t('organizer-dashboard-desc') %>
                </p>
              </div>
              <div class="col-xs-6">
                <p class="text-xs-center">
                  <%= image_tag("guidebook-luggage.svg", :alt => "new truppie", :width => 200, :class => 'img-fluid center-block') %>
                </p>
                <p class="text-xs-center">
                  <%= link_to guidebooks_organizer_path(@organizer), class: 'btn btn-primary btn-lg', data: {turbolinks: false} do %>
                      <%= t('organizer-new-guidebook') %> <i class="fa fa-plus"></i>
                  <% end %>
                </p>
                <p class="text-xs-center">
                  <%= t('organizer-dashboard-guidebook-desc') %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div id="fullscreen_bg" class="fullscreen_bg"></div>
</div>

app/views/organizers/index.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div style="margin-top: 40px">
      <% if @organizers.any? %>
          <%= render partial: 'layouts/guides_list', locals: {guides: @organizers} %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/organizers/manage_guidebooks.html.erb
<%= render 'layouts/navbar' %>
  <div class="container manage-entries">
    <div class="row">
      <div class="col-xs-12">
        <div class="manage-inspiration">
          <%= render 'layouts/organizer_intro_block', locals: {organizer: @organizer} %>
        </div>
        <div class="manage-inspiration">
          <%= render 'layouts/organizer_dashboard_reservations', locals: {organizer: @organizer} %>
        </div>
        <div class="card card-block trigger-overlay-container">
            <p><a href="#" id="js-trigger-overlay" class="btn btn-block btn-primary trigger-overlay"><strong>ver balanço de outras truppies</strong></a></p>
        </div>
        <div class="manage-container">
          <div class="manage-sidebar overlay-effect overlay">
              <button type="button" class="close">Close</button>
              <h2 class="spaced-down">Roteiros</h2>
              <nav class="scroll">
                <ul class="flex-scroll">
                <% @guidebooks.each do |t| %>
                <li class="flex-nav-item">
                  <div class="manage-card <%= 'manage-selected' if t.id == @guidebook.id %>">
                    <div class="manage-card-visa">
                      <%= link_to manage_guidebooks_organizer_path(@organizer, t) do %>
                        <% if t.try(:picture) %>
                          <%= image_tag(t.picture(:thumbnail), :alt => t.organizer.name, :class=> "image-fluid") %>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="manage-card-number">
                      <%= link_to t.title, manage_guidebooks_organizer_path(@organizer, t) %>
                    </div>
                    <div class="manage-card-val">
                      Valor: <%= raw t.price %> <br />
                    </div>
                  </div>
                </li>
                <% end %>
                </ul>
              </nav>
          </div>
          <% if !@guidebook.nil? %>
          <div class="manage-main">
            <h2>
              <%= link_to @guidebook.title, guidebook_path(@guidebook) %></p>
            </h2>
            <h3><%= @guidebook.orders.count %> reserva(s):</h3>
            <% @guidebook.orders.each do |o| %>
            <div class="manage-item">
              <div class="manage-item-name"><%= raw(o.friendly_status(o.current_status)) %></div>
              <div class="manage-item-name"><%= o.user.name %></div>
              <div><%= o.amount %> reserva(s) de <%= raw final_price_from_cents(o.price) %></div>
              <div class="manage-item-description">
                <strong><%= o.payment_method %></strong><br />
                <small>Feita em <%= l(o.created_at, format: '%d de %B de %Y às %Hh%M') %></small> 
              </div>
              <div class="manage-item-price">
              </div>
            </div>
            <% end %>
          </div>
          <% else %>
              <div class="manage-main">
                <p class="text-xs-center"><strong><%= t('hello-organizer-welcome', organizer: @organizer.name) %></strong></p>
                <p class="text-xs-center"><%= t('organizer-account-intro-title') %></p>
                <p class="text-xs-center"><%= t('organizer-account-intro-desc') %></p>
                <p class="text-xs-center">
                  <%= image_tag("tent-mountain.svg", :alt => "new truppie", :width => 128, :class => 'img-fluid center-block') %>
                </p>
                <p class="text-xs-center">
                  <%= t('organizer-dashboard-desc') %>
                </p>
                <p class="text-xs-center">
                  <%= link_to account_edit_organizer_path(@organizer), class: 'btn btn-primary btn-lg' do %>
                      <%= t('organizer-add-account-data') %> <i class="fa fa-edit" style="margin-left: 5px;"></i>
                  <% end %>
                </p>
                <p class="text-xs-center">
                  <%= link_to guided_tour_organizer_path(@organizer), class: 'btn btn-primary btn-lg' do %>
                      <%= t('organizer-add-tour') %> <i class="fa fa-calendar" style="margin-left: 5px;"></i>
                  <% end %>
                </p>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  <div id="fullscreen_bg" class="fullscreen_bg"/>   
</div>
</div>

app/views/organizers/welcome.html.erb
bem vindo guias