config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forms
  resources :destinations
  resources :comments
  resources :guidebooks
  root 'welcome#index'

  mount MailyHerald::Webui::Engine => "/maily_webui"

  resources :backgrounds
  resources :collaborators
  resources :customers
  resources :tour_pictures
  resources :bank_accounts do
    member do
      get 'activate', to: 'bank_accounts#activate', as: 'activate'
    end
  end
  resources :marketplaces do
    member do
      get 'activate', to: 'marketplaces#activate', as: 'activate'
      get 'update_account', to: 'marketplaces#update_account', as: 'update_account'
      get 'request_external_payment_type_auth', to: 'marketplaces#request_external_payment_type_auth', as: 'request_external_payment_type_auth'
      get 'redirect', to: 'marketplaces#redirect', as: 'redirect'
    end
  end
  resources :translations

  resources :packages
  resources :services

  get 'tags/index'
  get 'languages/index'
  get 'places', to: 'wheres#place', as: 'places'

  get 'contacts/index'
  post 'contacts/send_form'
  post 'contacts/send_message'

  get 'welcome/organizer', to: 'welcome#organizer', as: 'organizer_welcome'
  get 'welcome/user', to: 'welcome#user', as: 'user_welcome'

  resources :orders

  resources :wheres

  post 'webhook', to: 'orders#webhook'
  post 'webhook_external_payment', to: 'orders#webhook_external_payment'
  post 'redirect_external', to: 'orders#redirect_external'
  get 'new_webhook', to: 'orders#new_webhook'
  get 'redirect', to: 'marketplaces#redirect'

  get 'flights/nearest_airports', to: 'flights#nearest_airports'

  get 'organizers/create_from_auth', to: 'organizers#create_from_auth', as: 'create_from_auth'
  get 'organizers/invite', to: 'organizers#invite', as: 'invite'
  get 'organizers/accept_invite/(:id)/(:token)', to: 'organizers#accept_invite', as: 'accept_invite'
  post 'organizers/send_invite', to: 'organizers#send_invite', as: 'send_invite'

  resources :organizers do
    member do
      get 'manage/tours/(:tour)', to: 'organizers#manage_tours', as: 'manage_tours'
      get 'manage/guidebooks/(:guidebook)', to: 'organizers#manage_guidebooks', as: 'manage_guidebooks'
      get 'marketplace', to: 'organizers#marketplace', as: 'marketplace'
      get 'transfer', to: 'organizers#transfer', as: 'transfer'
      post 'transfer_funds', to: 'organizers#transfer_funds', as: 'transfer_funds'
      get 'tos_acceptance', to: 'organizers#tos_acceptance', as: 'tos_acceptance'
      post 'tos_acceptance_confirm', to: 'organizers#tos_acceptance_confirm', as: 'tos_acceptance_confirm'
      get 'dashboard', to: 'organizers#dashboard', as: 'dashboard'
      get 'account', to: 'organizers#account', as: 'account'
      get 'account_edit', to: 'organizers#account_edit', as: 'account_edit'
      get 'profile_edit', to: 'organizers#profile_edit', as: 'profile_edit'
      get 'bank_account_edit', to: 'organizers#bank_account_edit', as: 'bank_account_edit'
      get 'account_status', to: 'organizers#account_status', as: 'account_status'
      get 'confirm_account', to: 'organizers#confirm_account', as: 'confirm_account'
      get 'guided_tour', to: 'organizers#guided_tour', as: 'guided_tour'
      get 'guidebooks', to: 'organizers#guidebooks', as: 'guidebooks'
      get 'schedule', to: 'organizers#schedule', as: 'schedule'
      get 'clients', to: 'organizers#clients', as: 'clients'
      get 'external_events', to: 'organizers#external_events', as: 'external_events'
      post 'import_events', to: 'organizers#import_events', as: 'import_events'
      get 'edit_guided_tour/(:tour)', to: 'organizers#edit_guided_tour', as: 'edit_guided_tour'
      get 'edit_guidebook/(:guidebook)', to: 'organizers#edit_guidebook', as: 'edit_guidebook'
    end
  end

  get 'tours/products', to: 'tours#products'
  get 'tours/products/:id', to: 'tours#product', as: 'tour_product'
  get 'tours/product_availability/:code', to: 'tours#product_availability'
  post 'tours/confirm_product', to: 'tours#confirm_product'
  post 'tours/confirm_product_booking', to: 'tours#confirm_product_booking'

  resources :tours do
    member do
      get 'confirm/(:packagename)', to: 'tours#confirm', as: 'confirm'
      get 'copy_tour', to: 'tours#copy_tour', as: 'copy_tour'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'show_interest', to: 'tours#show_interest'
    end
  end

  resources :guidebooks do
    member do
      get 'confirm/(:packagename)', to: 'guidebooks#confirm', as: 'confirm'
      get 'copy_guidebook', to: 'guidebooks#copy_guidebook', as: 'copy_guidebook'
      post 'confirm_presence'
      get 'confirm_presence_alt'
      post 'unconfirm_presence'
      get 'manage/guidebook/(:guidebook)', to: 'organizers#guidebook', as: 'manage'
    end
  end

  post 'subscribers/create'

  devise_for :users, :controllers => {
    :passwords => "users/passwords",
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions"
  }

  resources :users do
    member do
      get 'follow', to: 'users#follow'
      get 'unfollow', to: 'users#unfollow'
    end
  end

  get 'logos' => 'welcome#logos'
  get 'manifest' => 'welcome#manifest'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'privacy' => 'welcome#privacy'
  get 'defs' => 'welcome#defs'
  get 'faq' => 'welcome#faq'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ApplicationHelper

  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:my_locale] = l
    redirect_to request.referer || root_url
  end

  def index
    @tours = Tour.publisheds
    @next_tour = Tour.recents.first
    @next_tours = Tour.publisheds.nexts
    @past_tours = Tour.publisheds.past
    @organizers = Organizer.publisheds.order(created_at: :asc)
    @guidebooks = Guidebook.publisheds
    @wheres = Where.last(4).reverse
  end

  def organizer
    if current_user
      @organizer = Organizer.find_by(user_id: current_user.id)
      if @organizer
        redirect_to profile_edit_organizer_path(@organizer)
      else
        @new_organizer = Organizer.new
      end
    else
      if !@new_organizer
        @new_organizer = Organizer.new
      end
    end
  end

  def user
    @backgrounds = Background.all
  end

  def logos

  end

  def manifest
    locale = I18n.locale || params[:locale].to_s
    @page = AdminPage.where(lang: locale, namespace: 'manifest').first
  end

  def how_it_works
    locale = I18n.locale || params[:locale].to_s
    @page = AdminPage.where(lang: locale, namespace: 'how_it_works').first
  end

  def privacy
    locale = I18n.locale || params[:locale].to_s
    @page = AdminPage.where(lang: locale, namespace: 'privacy').first
  end

  def defs

  end

  def faq
    locale = I18n.locale || params[:locale].to_s
    @page = AdminPage.where(lang: locale, namespace: 'faq').first
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/defs.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h3 class="spaced-default">
			  <%= t('welcome_view_defs_h3') %>
			  <small class="text-muted"><%= t('welcome_view_defs_small') %></small>
			</h3>
			<p><%= t('welcome_view_defs_p_1') %></p>
			<p><%= t('welcome_view_defs_p_2') %></p>
			<p><%= t('welcome_view_defs_p_3') %></p>	
		</div>
	</div>
</div>

app/views/welcome/faq.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<br>
			<%= raw(@page.body) %>
		</div>
	</div>
</div>

app/views/welcome/how_it_works.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<br>
			<%= raw(@page.body) %>
		</div>
	</div>
</div>

app/views/welcome/manifest.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<br>
			<%= raw(@page.body) %>
		</div>
	</div>
</div>

app/views/welcome/old_organizer.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 wow bounceIn">
      <% if !@organizer.nil? %>
          <p class="spaced-smallest">
            <%= t('for-you-on-truppie-title') %>
          </p>
          <nav class="navbar navbar-light bg-faded">
            <%= link_to organizer_path(@organizer), class: 'navbar-brand' do %>
                <i class="fa fa-map-o"></i> <strong><%= @organizer.name %>: </strong>
            <% end %>
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <%= link_to manage_tours_organizer_path(@organizer), class: 'nav-link' do %>
                    <%= t('manage-truppie-action') %>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to transfer_organizer_path(@organizer), class: 'nav-link' do %>
                    <%= t('transfer-truppie-action') %>
                <% end %>
              </li>
            </ul>
          </nav>
      <% end %>
    </div>
  </div>
  <div class="row wow bounceIn">
    <div class="col-xs-12">
      <div class="jumbotron" style="margin-top: 40px;">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <h4 class="display-5 spaced-down"><%= t('want-offer-truppies-title') %> </h4>
            <p><%= t('organizer-why-create-account-text') %></p>
            <p>
              <% if !@organizer.nil? %>
                <p><%= link_to t('profile-access'), organizer_path(@organizer), class: 'btn btn-primary btn-lg' %></p>
                <p><%= t('profile-access-truppie-account') %></p>
                <ul class="list-group spaced-down">
                  <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('profile-access-truppie-account-step') %></li>
                  <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('profile-access-truppie-account-transfer-step') %></li>
                  <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('profile-access-truppie-account-share-step') %></li>
                </ul>
            <% else %>
                <p><%= t('create-truppie-account') %></p>
                <p><%= t('organizer-after-create-account-advantages') %></p>
                <p><strong><%= t('after-create-truppie-account') %></strong></p>
                <ul class="list-group spaced-down">
                  <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('create-account-action-step') %></li>
                  <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= link_to t('contact-us-action-step'), contacts_index_path %></li>
                  <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('organizer-access-step') %></li>
                </ul>
                <p><%= link_to t('enter-login'), new_user_session_path, class: 'btn btn-primary btn-lg' %></p>
            <% end %>
            </p>
          </div>
          <div class="col-xs-12 col-md-6">
            <%= image_tag("screenshots/organizer-profile-mobile.png", :alt => "Truppie", :class => "img-fluid") %>
          </div>
        </div>
      </div>
      <h2 class="spaced-top"><%= t('offer-truppie-advantages') %></h2>
    </div>
  </div>
  <div class="row wow bounceIn">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <%= image_tag("screenshots/organizer-balance-desktop.png", :alt => "Truppie", :class => "img-fluid") %>
        </div>
        <div class="col-xs-12 col-md-6">
          <%= image_tag("screenshots/organizer-balance.png", :alt => "Truppie", :class => "img-fluid") %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <p><%= t('offer-truppies-title-call') %></p>
          <ul class="list-group spaced-down">
            <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('admin-payment-with-us-step') %></li>
            <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('admin-payment-with-us-limit-step') %></li>
            <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('admin-payment-with-us-final-step')%></li>
          </ul>
          <p><%= t('admin-payment-with-us-conclusion') %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="row cards">
        <div class="col-sm-4 wow bounceIn">
          <div class="card card-block text-xs-center">
            <h4 class="card-title main-color-font">
              <%= image_tag("mobile-friendly.jpg", :alt => "Truppie", :class => "img-fluid symbol-big") %>
              <p class="tagline emblem-font"><%= t('admin-from-anywhere-title') %>
            </h4>
            <p class="card-text"><p class="tagline emblem-font"><%= t('admin-from-anywhere-content') %></p>
          </div>
        </div>
        <div class="col-sm-4 wow bounceIn">
          <div class="card card-block text-xs-center">
            <h4 class="card-title main-color-font">
              <picture>
                <%= image_tag("secure-payment.jpg", :alt => "Truppie", :class => "img-fluid symbol-big") %>
              </picture>
              <p class="tagline emblem-font"><%= t('admin-secure-payment-title') %>
            </h4>
            <p class="card-text"><p class="tagline emblem-font"><%= t('admin-secure-payment-content') %></p>
          </div>
        </div>
        <div class="col-sm-4 wow bounceIn">
          <div class="card card-block text-xs-center">
            <h4 class="card-title main-color-font">
              <%= image_tag("facebook-share.jpg", :alt => "Truppie", :class => "img-fluid symbol-big") %>
              <p class="tagline emblem-font"><%= t('admin-share-event-title') %>
            </h4>
            <p class="card-text"><p class="tagline emblem-font"><%= t('admin-share-event-content') %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-12'>
      <%= render partial: 'layouts/subscribe' %>
    </div>
  </div>
</div>

app/views/welcome/organizer.html.erb
<% content_for :body_class, "mountain-form" %>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "mountain-form.js", defer: true %>
<% end %>
<%= render 'layouts/navbar' %>
<%= render 'layouts/flash' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if @organizer %>
        <div style="margin-top: 20px; margin-bottom: 20px">
          <div class="bg-warning">
            <%= t('title-introducing-accounts') %>
          </div>
        </div>
        <% @organizer.each do |o| %>
              <nav class="navbar navbar-light bg-faded spaced-down">
                <%= link_to organizer_path(o), class: 'navbar-brand' do %>
                    <i class="fa fa-map-o"></i> <%= o.name %>
                <% end %>
                <ul class="nav navbar-nav">
                  <li class="nav-item">
                    <%= link_to dashboard_organizer_path(o), class: 'nav-link' do %>
                        <%= t('panel-label') %>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to manage_tours_organizer_path(o), class: 'nav-link' do %>
                        <%= t('balance-label') %>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to transfer_organizer_path(o), class: 'nav-link' do %>
                        <%= t('transfer-label') %>
                    <% end %>
                  </li>
                </ul>
              </nav>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="container container-mountain">
  <div class="row no-gutters">
    <div class="col-12 col-sm-6">
      <div class="container container-moutain-join-truppie">
        <div class="row">
          <div class="lbg">
          </div>
          <div class="lbg2">
          </div>
          <div class="lO">
          </div>
          <div class="lC">
            <h1><%= t('title-organizer-join-truppie') %></h1>
            <p></p>
            <h3 style="margin-bottom: 20px;"><%= t('desc-organizer-why-truppie') %></h3>

            <% if user_signed_in? %>
                <div class="row py-2">
                  <div class="col-sm-3 hidden-md-down">
                    <%= image_tag current_user.image, class: "img-circle", width: "50" %>
                  </div>
                  <div class="col-sm-9">
                    <small><%= t('logged-as-label') %></small>
                    <p><%= current_user.name %></p>
                    <%= link_to t('logout-label'), destroy_user_session_url, class: "btn btn-primary btn-xs" %>
                  </div>
                </div>
                <!-- row end -->
            <% else %>
                <%= link_to omniauth_authorize_path(:user, 'facebook'), class: 'btn btn-social btn-facebook' do %>
                    <span class="fa fa-facebook"></span> <%= "Entrar com o #{OmniAuth::Utils.camelize('facebook')}" %>
                <% end %>
            <% end %>
            <div class="progress-state-container" style="position:absolute; bottom: 0; left: 120px;">
              <div class="progress_state">
                <div class="dot" id="dot1" style="opacity: 1;"></div>
                <div class="dot" id="dot2" style="opacity: 0.3;"></div>
                <div class="dot" id="dot3" style="opacity: 0.3;"></div>
                <div class="dot" id="dot4" style="opacity: 0.3;"></div>
                <div class="dot" id="dot5" style="opacity: 0.3;"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-6">
      <%= form_for @new_organizer, role: "form", method: 'POST', multipart: true do |f| %>
        <div class="rightSec" id="first">
          <ul class="spaced-top">
            <li>
              <label>
                <%= t('label-organizer-name') %>
              </label>
              <%= f.text_field :name %>
              <% if flash[:errors] and flash[:errors].key?(:name) %>
                <span class='glyphicon glyphicon-exclamation-sign text-danger pull-right icon-style'></span>
                <small class="text-danger"><%= error_message_text(flash[:errors], :name) %></small>
              <% else%>
                <span class="required">*</span>
              <% end %>
            </li>
            <li>
              <label>
                <%= t('label-organizer-email') %>
              </label>
              <%= f.email_field :email %>
              <% if flash[:errors] and flash[:errors].key?(:email) %>
                  <span class='glyphicon glyphicon-exclamation-sign text-danger pull-right icon-style'></span>
                  <small class="text-danger"><%= error_message_text(flash[:errors], :email) %></small>
              <% else%>
                  <span class="required">*</span>
              <% end %>
              <%= f.hidden_field :type_of_user, value: 'organizer' %>
            </li>
            <% if current_user.try(:id) %>
                <%= f.hidden_field :user_id, value: current_user.try(:id) %>
            <% else %>
            <li>
              <label>Senha</label>
              <%= f.password_field :password, autocomplete: "off" %>
              <% if flash[:errors] and flash[:errors].key?(:password) %>
                  <span class='glyphicon glyphicon-exclamation-sign text-danger pull-right icon-style'></span>
                  <small class="text-danger"><%= error_message_text(flash[:errors], :password) %></small>
              <% else%>
                  <span class="required">*</span>
              <% end %>
            </li>
            <li>
              <label>Confirmar senha</label>
              <%= f.password_field :password_confirmation, autocomplete: "off" %>
              <% if flash[:errors] and flash[:errors].key?(:password_confirmation) %>
                  <span class='glyphicon glyphicon-exclamation-sign text-danger pull-right icon-style'></span>
                  <small class="text-danger"><%= error_message_text(flash[:errors], :password_confirmation) %></small>
              <% else%>
                  <span class="required">*</span>
              <% end %>
            </li>
            <% end %>
            <li>
              <label>
                <%= t('label-organizer-website') %>
              </label>
              <%= f.text_field :website %>
              <% if flash[:errors] and flash[:errors].key?(:website) %>
                  <span class='glyphicon glyphicon-exclamation-sign text-danger pull-right icon-style'></span>
                  <small class="text-danger"><%= error_message_text(flash[:errors], :website) %></small>
              <% else%>
                  <span class="required">*</span>
              <% end %>
            </li>
            <li>
              <label><%= t('label-organizer-about') %></label>
              <%= f.text_area :description, rows: 2 %>
              <% if flash[:errors] and flash[:errors].key?(:description) %>
                  <span class='glyphicon glyphicon-exclamation-sign text-danger pull-right icon-style'></span>
                  <small class="text-danger"><%= error_message_text(flash[:errors], :description) %></small>
              <% else%>
                  <span class="required">*</span>
              <% end %>
            </li>
          </ul>
          <div class="nav_link">
            <a href="#" id="continue" data-turbolinks="false" style="float:right;"><%= t('label-organizer-continue') %></a>
          </div>
          <% if flash[:errors].nil? %>
            <div class="required_fields_message">* <%= t('label-organizer-required-fields-messsage') %></div>
          <% end %>
        </div>


        <!-- Section 2 -->

        <div class="rightSec" id="second" style="display:none">
          <ul>
            <li>
              <label>
                <%= t('label-organizer-address-city') %>
              </label>
              <input type="text" name="search" placeholder="<%= t('place') %>" class="places-input" />
              <%= f.fields_for :wheres, (Array.new(1, @new_organizer.wheres.build) if @new_organizer.wheres.empty?) do |ff| %>
                  <%= ff.hidden_field :name %>
                  <%= ff.hidden_field :lat %>
                  <%= ff.hidden_field :long %>
                  <%= ff.hidden_field :city %>
                  <%= ff.hidden_field :state %>
                  <%= ff.hidden_field :country %>
                  <%= ff.hidden_field :postal_code %>
                  <%= ff.hidden_field :address %>
                  <%= ff.hidden_field :url %>
                  <%= ff.hidden_field :google_id %>
                  <%= ff.hidden_field :place_id %>
              <% end %>
              <div id="map"></div>
            </li>
          </ul>
          <div class="nav_link">
            <a href="#" data-turbolinks="false" id="prev"><%= t('label-organizer-previous') %></a>
            <a href="#" data-turbolinks="false" id="continue2" style="float:right;"><%= t('label-organizer-continue') %></a>
          </div>
        </div>

        <!--- Secont 3 --->

        <div class="rightSec" id="third" style="display:none">

          <ul>
            <li>
              <label>
                <%= t('label-organizer-phone') %>
              </label>
              <%= f.text_field :phone %>
            </li>
            <li>
              <label>
                <%= t('label-organizer-instagram') %>
              </label>
              <%= f.text_field :instagram %>
            </li>
            <li>
              <label>
                <%= t('label-organizer-facebook') %>
              </label>
              <%= f.text_field :facebook %>
            </li>
            <li>
              <label>
                <%= t('label-organizer-twitter') %>
              </label>
              <%= f.text_field :twitter %>
            </li>
          </ul>


          <div class="nav_link">
            <a href="#" data-turbolinks="false" id="prev2"><%= t('label-organizer-previous') %></a>
            <a href="#" data-turbolinks="false" id="continue3" style="float:right;"><%= t('label-organizer-continue') %></a>
          </div>
        </div>


        <!-- Section 4 -->

        <div class="rightSec" id="fourth" style="display:none">
          <ul>
            <li>
              <label>
                <%= t('label-organizer-picture') %>
              </label>
              <%= f.file_field :picture %>
            </li>
          </ul>
          <div class="nav_link">
            <a href="#" id="prev3"><%= t('label-organizer-previous') %></a>
            <a href="#" id="continue4" style="float:right;"><%= t('label-organizer-continue') %></a>
          </div>
        </div>
        <div class="rightSec" id="fifth" style="display:none">
          <div class="ty">
            <h1><%= t('label-organizer-thanks') %></h1>
            <h3><%= t('label-organizer-thanks-email') %></h3>
            <h5><%= t('label-organizer-thanks-moderation') %></h5>
            <button type="submit" value="submit"><%= t('label-organizer-finish') %></button>

          </div>
          <div class="nav_link">
            <a href="#" data-turbolinks="false" id="prev4"><%= t('label-organizer-previous') %></a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/privacy.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<br>
			<%= raw(@page.body) %>
		</div>
	</div>
</div>

app/views/welcome/user_copy2.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2 class="spaced-default"><%= t('user-adventure-info') %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <figure id="showcase">
        <section></section>
        <section></section>
        <section></section>
        <section></section>
      </figure>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <p><%= t('user-adventure-step') %></p>
      <p><%= t('user-what-truppie-is') %></p>
      <p><%= t('user-truppie-possibilities') %></p>
      <ul class="list-group spaced-down">
        <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('user-advantages-payment-step') %></li>
        <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('user-advantages-discover-step')%></li>
        <li class="list-group-item"><i class="fa fa-hand-o-right"></i> <%= t('user-advantages-guide-contact-step')%></li>
      </ul>
      <p><%= t('user-advantages-conclusion') %></p>
    </div>
    <div class="col-xs-12 col-md-6">
      <%= image_tag("screenshots/user-order-desktop.png", :alt => "Truppie", :class => "img-fluid") %>
    </div>
  </div>
  <%= render partial: 'layouts/what_it_is' %>
  <div class="row">
    <div class="col-xs-12">
      <div class="jumbotron">
        <h2 class="display-5"><%= t('user-collect-experience-title')%></h2>
        <p class="lead"><%= t('user-why-truppie-is-so-great')%></p>
        <p><%= t('user-why-truppie-is-so-great-complement')%></p>
        <p class="lead">
          <%= link_to t('user-start-to-use-truppie'), root_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>
  </div>
</div>